### ISSUE TITLE
Think about a run.sh replacement 

### ISSUE THREAD

**Issue by stephenh** [stephenh/joist-ts#190]
- Loading
  - Production code path should never load the env
  - Tests need to load the env from Webstorm/vscode, done in `setupTests`?
    - Could use `setupTestEnv.js`, set `process.env.STAGE=local` and require `dotenv-stages`
  - Scripts need to load the env (migrations, console), done in `run.sh`?
    - Could set `STAGE=local` and pass `-r dotenv-stages`
  - `docker-compose` needs to load the env, done in `docker-compose.yml`?
    - Could set `STAGE=local+docker` and `NODE_OPTIONS=-r dotnev-stages`

* `STAGE=local+docker,test`
* Look for `NODE_ENV=test`?
* How do detect within docker?

**Comment by mmahalwy** [comment]
A replace could be having `/bin` for joist-codegen?

**Comment by mmahalwy** [comment]
@stephenh thoughts on removing this

**Comment by stephenh** [comment]
@mmahalwy `run.sh` is just a convenience method for "run ts-node with some env defaults and some `-r` defaults", i.e. nothing core/really related to Joist itself, so downstreams projects are free to invoke their tests / the joist codegen / etc. however they want.

(I.e. Just running `npx run joist-codegen` would probably work if you had the database env arg(s) already setup.)

That said, I would like to have a cuter way of doing this, just for our own internal projects + to copy/paste around in Joist sample apps, so I think we'll eventually think of an alternative, but for now it's not a high priority.

**Comment by ianwalter** [comment]
I would suggest using [env-cmd](https://github.com/toddbluhm/env-cmd) and .env files.

**Comment by stephenh** [comment]
Thanks for the suggestion @ianwalter !
