### ISSUE TITLE
pg-structure error on postgres 14

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#201]
Running into this:
```
TypeError: typeKinds[kind] is not a constructor
    at /Users/mo/Desktop/code/playing-around/orm-comparison/node_modules/pg-structure/src/main.ts:171:12
    at Array.forEach (<anonymous>)
    at addTypes (/Users/mo/Desktop/code/playing-around/orm-comparison/node_modules/pg-structure/src/main.ts:166:8)
    at addObjects (/Users/mo/Desktop/code/playing-around/orm-comparison/node_modules/pg-structure/src/main.ts:368:3)
    at pgStructure (/Users/mo/Desktop/code/playing-around/orm-comparison/node_modules/pg-structure/src/main.ts:465:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/mo/Desktop/code/playing-around/orm-comparison/node_modules/joist-codegen/src/index.ts:190:16
```

When console logging, I see that `datemultirange` is not supported on pg-structure. 

```
{
  oid: 4535,
  arrayOid: 6155,
  schemaOid: 11,
  classOid: 0,
  kind: 'm',
  category: 'R',
  notNull: false,
  default: null,
  sqlType: null,
  arrayDimension: 0,
  name: 'datemultirange',
  values: '{}',
  comment: 'multirange of dates',
  relationKind: null
} m
```

**Comment by mmahalwy** [comment]
Related issue: https://github.com/ozum/pg-structure/issues/68

**Comment by stephenh** [comment]
I've opened https://github.com/stephenh/joist-ts/pull/202 to bump pg-structure, but I'm not putting "fixed #201" in it b/c I assume after getting past that pg-structure error, you're going to hit an error where then Joist itself doesn't support these new/fancy data types... :-/ I have admittedly only been flushing out pg data types as we personally need them, and haven't tried to exhaustively support all of the pg data types.

**Comment by mmahalwy** [comment]
No worries. We don't use those fancy types. It was more of a blocker for introspection and code gen

**Comment by stephenh** [comment]
Ah nice! Going to close this out then.
