### ISSUE TITLE
Forgetting to run `em.flush`

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#285]
Thoughts on how to solve developers forgetting to run `em.flush()`? Ran into a bug where I was doing `createOrUpdatePartial` and forgot to flush, therefore the validation error wasnt running. 

Thoughts?

**Comment by stephenh** [comment]
Yeah, no silver bullets... Two thoughts I guess:

1. In a prior system, each of our `PUT /author` / etc. endpoints was auto-wrapped by our infra in a "open EM" + "flush EM" middleware, so endpoints never had to worry about opening or flushing the EM, it was always just done for them.

For the minority case where a particularly complex endpoint needed to do its own EM management, i.e. to touch ~lots of entities, then it could go ahead and manually instantiate/management a few of them/as needed.

2. In our current system, our endpoint (now GraphQL resolver) tests specifically has its own "test EM" and then invokes the resolver with a dedicated/clean EM. This:

a) Ensures the resolver EM is not getting accidentally pre-loaded/accidentally pre-mutated data from whatever the test setup did, and that it really needs to work on its own accord.
b) Ensures the resolver EM does not forget to em.flush, b/c after the resolver finishes, and the test EM does it's assertions, b/c it's a separate EM, it won't see anything the resolver did, unless the resolver very specifically flushed the data to the database.

This 2nd approach has been working for us well, such that it's very rare to forget an `em.flush`, well, at least for it to get deployed to production. I agree there can be some "starring at the test" time lost to wondering "wtf did the data not save" for new engineers that don't know the `em.flush` incantation...

I don't have any great ideas for that; like _maybe_ some sort of `afterEach` that would tell Joist "please check any EMs instantiated during this test, and see if they are dirty, and fail if they are b/c the user probably forgot a flush"...

**Comment by mmahalwy** [comment]
@stephenh thanks for the answer. Makes sense. I guess, approach 2 assumes resolvers are tested – in our case we dont have full coverage :(

**Comment by stephenh** [comment]
Just tidying up, but the EntityManager is a foundational part of Joist that I think we'll just have to solve this with docs & education.
