### ISSUE TITLE
API returning entities does not include null fields

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#314]
Take example of joist vs prisma:
```ts
app.get('/testing', async (req, res) => {
  const users = await em.find(User, {});

  res.send(users);
});
app.get('/testing2', async (req, res) => {
  const users = await prisma.user.findMany();

  res.send(users);
});
```

Because we are using `res.send`, we aren't calling each field directly. This causes fields that are `null` to be missing. See:
joist:
```json
[
  {
    "role": "ADMIN",
    "id": "u:0c1b33c7-897a-4ca3-a116-9560d02ff48e",
    "createdAt": "2022-04-14T03:14:53.828Z",
    "updatedAt": "2022-04-14T03:14:53.829Z",
    "firstName": "Costas",
    "lastName": "Hadjipateras",
    "email": "costas@withshepherd.com",
    "phoneNumber": "(203) 246 2006",
    "imageUrl": "",
    "title": "Head of Underwriting"
  }
]
```

Prisma:
```json
[
  {
    "id": "a7635524-423b-4324-b88d-1544c2dd31e3",
    "firstName": "Steve",
    "lastName": "Buonpane",
    "email": "steve@withshepherd.com",
    "phoneNumber": "(631) 513 5253",
    "imageUrl": "",
    "role": "ADMIN",
    "title": "Chief Insurance Officer",
    "createdAt": "2022-04-13T23:14:53.828Z",
    "updatedAt": "2022-04-13T23:14:53.829Z",
    "lastLoggedIn": null,
    "slackUserId": null
  }
]
```

This is obviously not a problem with GraphQL. 

A potential fix is having a helper function that turns an entity into an object.

**Comment by stephenh** [comment]
@mmahalwy ah yeah, that's interesting...

FWIW I'd kinda forgot that `Entity.toJSON` even did that (echo-d all of the fields). I knew that we implemented `toJSON` "just in case" an entity was console.log-d / included in a response, but it was really meant to be a super official "JSON API".

So I'm a little hesitant to expand on this, vs. encouraging users to use some sort of "official" JSON API approach...

But it is interesting how close, basically by accident / happenstance, that Joist is close to what Prisma does, so, :shrug: I guess why not if it helps users migrate over...

@zgavin wdyt?

**Comment by stephenh** [comment]
@mmahalwy are you still relying on this functionality?

We've implemented more explicit `toJSON` support that takes a subset of fields, potentially nested, to turn into JSON:

https://joist-orm.io/docs/advanced/json-payloads

And I'm thinking it is more safer to make the default `toJSON()` output be just an id, to avoid accidentally putting sensitive information on the wire.
