### ISSUE TITLE
Tables with Self-Referencing ForeignKeys

### ISSUE THREAD

**Issue by TylerR909** [stephenh/joist-ts#582]
If you're trying to set up a `Book.nextBook` chain, Codegen is double-injecting `nextBook` into `BookCodegen.ts`.

Specifically using: `foreignKey("books", { notNull: false, unique: true })`. 

An additional implication is that eventually, you reach the "latest" book such that `book.nextBook === undefined`

**Comment by stephenh** [comment]
Pretty sure this works:

https://github.com/stephenh/joist-ts/pull/603/files

I'm unclear how Joist would end up using `nextBook` twice, i.e. here it used `sequel` (from the original book.sequel_id -> sequel book FK) and then `sequelBook` (back from the sequel to the original).

Granted, `sequelBook` is a nonsense name, but that's just b/c Joist does not know "the opposite of sequel".

My guess is that whatever production entity your in as other relations than just this self-referencing FK that are leading to the collision.

Or maybe there was a bug in Joist's "guess the o2o other side" mode...definitely possible.

That said, the new renaming-in-the-migration should for sure solve this:

```
    sequel_id: foreignKey("books", { notNull: false, unique: true, otherFieldName: "original" }),
```

Produces `Book.sequel` and `Book.original` with no overlaps and pleasant/sensical names, so going to close this out. Lmk if you still have observed bad behavior.
