### ISSUE TITLE
Add The Ability to add flush_database() to Test Database without generating code

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#585]
I'm running Jest in multiple threads where each thread has a separate database.  In order to have flush_database() available I have to re-run the code generation for each database. 

Occasionally this will cause errors because the destination files are being written by more than on process at a time.

**Comment by stephenh** [comment]
Ah yeah, that makes sense... fwiw I guessed a little bit about a solution, of just hard-coding your test db names in `joist-config.json` as the value of the `createFlushFunction` key.

Does that work out? Let me know if not and we can try a different approach.

Thanks!
