### ISSUE TITLE
newTestInstance unnecessarily creates associations for non-required fields

### ISSUE THREAD

**Issue by chr1sjf0x** [stephenh/joist-ts#62]
If a field is not required, and not specified in the opts, then newTestInstance should not associate it to an existing entity.

If I have:
```
Author {
  book?: Book
}

Then call:
const a1 = newTestInstance(em, Author, { name: "A1", book: { title: "I'm a book by A1" } });
const a2 = newTestInstance(em, Author, { name: "A2" });

// This will fail
expect(a1.book).not.toEqual(a2.book)
```

**Comment by stephenh** [comment]
Yeah, per standup update, I think this ends up being a 50/50...with the disclaimer that I've technically forgotten the use case that nudged this over to the current "_do_ fill in unrequired entities" vs. the previous behavior that you're proposing...

Fwiw I think passing `null` like `const a1 = newTestInstance(em, Author, { name: ..., book: null } }` will keep this from being filled in?

**Comment by chr1sjf0x** [comment]
Yes, the explicitly setting it to `null` does provide the desired functionality. TY!
