### ISSUE TITLE
Feature Request: Separate Codegen Directory for 100% Generated Files

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#635]
A low priority for sure, I'd like to have a separate directory for purely generated files vs the files I will change.

For example I put all my entities in an `entities` folder. I'd like to have `entities/codegen` for all the files I should never worry about and in `entities` have the files I maintain after they are initially generated.

**Comment by stephenh** [comment]
Ah yeah! That's a good idea.

**Comment by brudil** [comment]
I have the start of this in a branch somewhere. I remember there being a couple of interesting decisions to make on the approach;

1. It's currently implemented an optional `"entitiesCodegenDirectory": "generated",` option - this isn't a path from root, but joined with whatever is in `entitiesDirectory`.

2. What is considered _generated_ - I started with the assumption of files that are marked as `overwrite`

a. Entity Codegen - yes
b. Enum - yes
c. PgEnum - yes
d. metadata.ts - yes
e. Entity - no
f. Factory - no
g. index.ts - no

**Comment by davekerber** [comment]
Yeah, generally speaking I want to have all the folders I don't need to review or maintain in a single folder. This makes PRs and tooling easier.  The list you created makes sense to me.
