### ISSUE TITLE
Tag assignment can generate JavaScript keywords which are used in codegen output

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#672]
When trying out joist-codegen on our existing application with a fair few tables, I noticed our freshly generated `DataObserverCodegen.ts` had syntax issues.

DataObserver, as you might imagine, gets assigned `do`. Inside the populate method, the tag ID is used for one of the parameter names, leading to syntax issues.

```ts
populate<H extends LoadHint<DataObserver>, V>(hint: H, fn: (do: Loaded<DataObserver, H>) => V): Promise<V>;
```

Obviously nicely avoidable with joist-codegen.json, so not exactly important but I thought it might be worth flagging as it was a fun one to realise.

**Comment by stephenh** [comment]
Ah! I'm actually surprised we haven't ran into that yet. :-) thanks for filing the issue...it should be pretty quick to fix.

But great that you found changing the tag as a good workaround.
