### ISSUE TITLE
jsonb columns don't support top level array

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#684]
Attempting to persist an array to a jsonb column results in `invalid input syntax for type json array`.

I've got a repro with some tests in this branch https://github.com/stephenh/joist-ts/commit/fea62a60107e8f8b335fbb9e4440195fb5097b65

Digging in to this, it looks like node-postgres assumes arrays are native pg arrays: https://github.com/brianc/node-postgres/issues/442

stringifying the array beforehand works, but as far as I can tell, joist passes the data directly.

I've got a basic workaround to validate my suspicions by doing a JSON.stringify within SuperstructSerdes (https://github.com/stephenh/joist-ts/commit/5dce2a3739a840cdf35640af707ffd875a65500e)

Although I'm questioning if this is the right place for it, for example using a type config instead if superstruct would not work. Perhaps if #678 and exposure land, it could be a user-land concern. But with Joist's runtime metadata of column types, it feels like there might be a better place (after serde) to do this before handing off to pg?

**Comment by stephenh** [comment]
Huh! Great find on that node-pg issue.

> using a type config instead if superstruct would not work

Do you mean like if the user is using a `jsonb` column _without_ using the `superstruct` config option? If so, agreed we should handle that, maybe via just a `JsonSerde` that we use for non-superstruct-configured jsonb columns?

Fwiw I think your changes to `SuperstructSerde` make a lot of sense / would be the rest place to do this, and the test case `quotes` / `string[]` is great.

If you want to turn that branch into a PR, that either handles this case for _just_ superstruct-configured fields or both superstruct-configured and superstruct-less (by introducing an additional JsonSerde), that'd be great! Thanks!

**Comment by brudil** [comment]
Will do!
