### ISSUE TITLE
CTI, timestamps and Oplocks

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#714]
We're currently investigating some issues around updating CTIs and hitting Oplocks.

I have a suspicison this is to do with merging of timestamps. Apologies if I've missed this from the docs, what are the semantics of timestamps between CTI'd entities.

We currently from our codebase migration have them on both, so I can imagine there might be issues here with which one is selected. But renaming (to avoid the conflict) on the sub tables, hasn't borne fruit. Perhaps we've got another issue, so really just curious if the semantics around CTI and Oplocks is defined. Otherwise we're happy to investigate.

**Comment by stephenh** [comment]
Hm, I'm not thinking of anything off hand...

I.e. looking at Joist's `Publisher` entity, it has the `created_at` + `updated_at` columns, and the `SmallPublisher` + `LargePublisher` entities/tables don't have them, with the idea that they'd defer to the base table's columns. 

Do your subtype tables have their own `created_at` + `updated_at` columns? I suppose that'd be fine if so, but yeah is probably not something that Joist expects.

Just checking, but if you have a `publishers` row with `id=1`, do you have only a _single_ entry in either `small_publishers` or `large_publishers`? Just asking b/c if there are both a `SmallPublisher` & `LargePublisher` entities/rows for the same `id=1`, that are trying to share the same base `Publisher` row, I could definitely see that causing oplock issues.

**Comment by brudil** [comment]
Cheers for the thoughts, we'll get to the bottom of this and report back anything interesting if we find it. We shouldn't have any dual sub instances.
