### ISSUE TITLE
cascadeDeleteFields & CTI

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#715]
`config.cascadeDelete()` doesn't seem to work for CTI entities when that config is on the parent. This introduces the need to duplicate this config each child class, even though the relationship is on the parent itself.

Happy to take this if this is considered a bug/fixable.

Have a couple thoughts/questions on impl; `cascadeDelete()` sets `__data.cascadeDeleteFields` on the config for each Entity's config. This is accessed in quite a few places on the Reference and Collection classes.

Such as

```ts
getMetadata(this.#entity).config.__data.cascadeDeleteFields
```

As I see it we've got two options here;

- Somehow set/replicate this on child entity configs also, allowing the above line to stay as is
- Within each usage, teach it about the concept of parent entities and collecting data from their config too

**Comment by stephenh** [comment]
Hey! Just catching up on things, but yep, that is a good find!

I think having a parent's cascade delete fields pushed into the child configs seems like a good approach...keeps the consumers simpler.

Maybe in `configureMetadata`, we could copy all `meta.config.__data.cascadeDeleteFields` down to the subtype metas?

We do basically the same thing in `configureMetadata` for `meta.fields` & `meta.allFields`--if we really needed to differentiate "my cascade delete fields" vs. "all cascade delete fields", we could add an additional array with the `allCascadeDeleteFields` convention, but thinking we probably? don't need that, and could get away with just one array...
