### ISSUE TITLE
Feature Request: Show Warnings for Unrecognized Fields

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#740]
I messed up configuring derived fields:

Instead of putting in my joist-config.json:
```json
{
  "entities": {
    "Book": {
      "fields": {
        "numberOfReviews": { "derived": "async" },
      },
      "tag": "b"
    }
  ...  
}
```

I put:
```json
{
  "entities": {
    "Book": {
      "fields": {
        "number_of_reviews": { "derived": "async" },
      },
      "tag": "b"
    }
  ...  
}
```

I was using the column name in the table instead of the field name in the class. When I ran the codegen step nothing was updated and there were no errors. 

It would be helpful if a warning was shown for unrecognized fields.

**Comment by stephenh** [comment]
Good suggestion!
