### ISSUE TITLE
Codegen should detect overlapping fields and fail sooner

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#762]
If a schema has both a `foo` primitive field and a `foo` m2o field (or any other overlap of fields), we don't detect it, and just output invalid TypeScript.

Which, granted the tsc will check with compile errors, but often test suites like ts-jest/etc don't type check anymore, and so opaque runtime errors will happen instead.

**Comment by stephenh** [comment]
Hm, can you copy/paste what the runtime failure is?
