### ISSUE TITLE
DATABASE_CONNECTION_INFO is not ergonomic

### ISSUE THREAD

**Issue by moltar** [stephenh/joist-ts#8]
Why not just use the defacto standard connection URI string. E.g. DATABASE_URI?

Stuffing JSON in an environment string is difficult in deployments that get the connection information from the environment.

**Comment by stephenh** [comment]
Yep; we run in AWS and so this is the AWS RDS connection "string"/JSON format that is created/stored in ECS.

So the current version is solely "this is what for works for now". Supporting the `postgres://` format makes a lot of sense.

**Comment by stephenh** [comment]
Just pushed conditionally using `pg-connection-string` if the `DATABASE_CONNECTION_INFO` doesn't look like JSON. Let me know if that doesn't work.

**Comment by moltar** [comment]
That is awesome. Thanks for that!
