### ISSUE TITLE
Make relations lazy

### ISSUE THREAD

**Issue by stephenh** [stephenh/joist-ts#836]
And initialized via getters. To avoid paying the cost of relation objects that you don't use.

https://github.com/evanwashere/mitata

Note that we'll need the laziness to be optional as well, b/c on boot we need to scan all relations/properties to setup reactivity dependencies, so it would only be post-boot instances that would want to have lazy relations.

**Comment by stephenh** [comment]
Maybe a tsx/esbuild/ts-patch plugin to rewrite user-written relations, i.e.:

```
  readonly reviews: Collection<Author, BookReview> = hasManyThrough((author) => author.books.reviews);
```

To:

```ts
  #reviews: Collection<Author, BookReview> | undefined;
  get reviews() { ...lazy init... }
```

**Comment by brudil** [comment]
Just chiming in here to say it would be great to support a solution that doesn't need additional preprocessing, even if it required additional API opt-in. It would be possible to utilise a single map to relations within, which could be part of the codegen/base entity.

Perhaps something like

```ts
  // base entity
  hasManyThrough(...args) {
    return lazy(this, hasManyThrough, args)
  }
   
 // codegen
 #relationsLazyMap: Map<int, Collection<any, any> | undefined;
  
  // user-land
 readonly reviews: Collection<Author, BookReview> = this.hasManyThrough((author) => author.books.reviews);
```

**Comment by stephenh** [comment]
Hey @brudil , yeah for sure any build-time things would be completely optional.

My guess is that the 1st version of this would be just relations in the codegen file, b/c the field + lazy getter is easy for the code generator to output.

But so far I've not been able to think of a way for non-codegen/user-defined relations to be similarly lazy... short of creating proxy/wrapper objects (similar I imagine your to your `lazy(...)` wrapper that would require profiling to know if it was really faster to create the proxy vs. just creating the relation directly.

Disclaimer a lot of this is speculative in that I don't really know for sure how expensive the relations are, i.e. we've not seen any production issues this would address; it was just a cute idea so I thought worth creating the ticket for it.

Even if the lazy-ness was only for codegen-based properties, I have to imagine that ~80-90% of relations in a typical domain model anyway, so I imagine that by itself, if there was going to be a perf increase, would still be worth it, and the user-defined properties would be overall a very small portion of relations, so more icing on the cake so to say, if we could lazy-ize them as well.

...also I need to note in the PR description, on boot we actually need relations to _not_ be lazy so we can do the instrumentation pass to discover the relation dependencies that drive our reactivity, so still some more thought required, about now to make the lazyness conditional.

**Comment by brudil** [comment]
I was forgetting that most relations are fully codegened anyway! I also assumed it was a memory thing, not a perf thing - you're right getting too fancy with the lazy part of it would invalidate those, if any, gains :)
