### ISSUE TITLE
Create a JSON schema for joist-config.json

### ISSUE THREAD

**Issue by stephenh** [stephenh/joist-ts#863]
Then submit it to:

https://www.schemastore.org/json/

https://www.jetbrains.com/help/webstorm/json.html#ws_json_schema_add_custom

**Comment by brudil** [comment]
One thing we previously hit and wouldn’t mind PR’ing is runtime validation of the config too. If this is a feature worth considering, it might be worth considering Zod or the like to perform this and generate a json schema automatically from it.

**Comment by stephenh** [comment]
Ah yeah, good idea! I was not looking forward to learning how to hand-write a JSON schema, so would be awesome to write zod instead, and let them create it for me. :-)

I like the runtime validation as well...I'm a little concerned that Joist depending on zod might create dependency issues if projects have their own version of zod. I know we have a soft-dependency on zod if you use it for jsonb columns, but it's more of a peer dependency & optional/etc...

Not that I want to "bundle all of zod", but it would be interesting to see if there was like a "zod-ish" way of doing the runtime validation, but that could be driven from a super-tiny file in the `src` folder, and not a dependency... :thinking: 

I'm also not zealous about "zero dependencies", but just thinking it through.

**Comment by brudil** [comment]
My thinking is that zod (or else) should be limited to joist-codegen and not joist-orm. So if my mental model of how dependencies are resolved is correct, it shouldn’t be an issue.
