### ISSUE TITLE
Bug: Import Not Using `entitiesDirectory`

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#880]
Just upgraded from 1.123.0 to 1.124.6 and regenerated files.  

After generating compilation fails with this error: 

```bash
error TS2307: Cannot find module 'src/entities' or its corresponding type declarations.
38 import { Entity } from "src/entities";
```

I have a custom entities directory configured in `joist-config.json`:

```json
{
  "entitiesDirectory": "./src/orm/entities"
}
```

Looks like this import isn't using that?

**Comment by stephenh** [comment]
@davekerber thanks for the report, should be fixed! I haven't technically setup a tests project with a non-src/entities directory yet, so let me know if not.

**Comment by davekerber** [comment]
All fixed up.  Thanks!
